### PR TITLE
Add Split Library support to ingestor

### LINKED ISSUE #92: [bug] Separate Book Files from Library
**Description**
Split metadata/books options is not being respected

**To Reproduce**
- New Instance using this
```yaml
calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=100
      - TZ=UTC
      - DOCKER_MODS=lscr.io/linuxserver/mods:universal-calibre-v7.16.0
    volumes:
      - ${CONFIG_ROOT:-.}/calibre/config-cwa:/config
      - ${CONFIG_ROOT:-.}/calibre/config-cwa/calibre-library:/calibre-library
      - ${APPHOME_ROOT}/book-ingest:/cwa-book-ingest
      - ${DATA_ROOT}/books:/books
    ports:
      - 8084:8083
```
- Set database config to use /calibre-library and /books
image
- Copy files into cwa-book-inject
- Click Refresh Library

**Expected behavior**
Books should be in /books but are ending up in the /calibre-library

**Unexpected behavior**
Setting the database config as above breaks the cover images 
Downloads 404

**Configuration(please complete the following information):**
 - OS: Ubuntu Server
 - Hardware: x86 server
 - Version: Latest?

**Additional context**
No original database/config. I've removed the config dir and started over with each test

CONFIG_ROOT is local
Other *_ROOTS are on NAS

### PR DESCRIPTION
**Pull request by tucker87**
I'm attempting to fix my own issue. But I've never written Python. These edits were made in browser.

I looked at CW's code for handling this and mimicked it.

**This is untested.**
Would appreciate feedback/help.

Fixes #92

### CODE REVIEW

**Comment by tucker87** [comment]
Looks like the author implented these changes in

48b039bb3e9de6d0ff77c4407b1854091e921f5e

Thanks!

**Comment by MrLemur** [comment]
@tucker87 Has this actually worked for you? The changes still cause the book to be added to the wrong folder, plus the book ingest function is broken now due to a misspelled variable name.

**Comment by tucker87** [comment]
I did not test the author's version. I just saw the conflicts when I went to rebase and realized they had done basically the same thing.

**Comment by jmarmstrong1207** [comment]
> @tucker87 Has this actually worked for you? The changes still cause the book to be added to the wrong folder, plus the book ingest function is broken now due to a misspelled variable name.

Which variable and error are you referencing?

**Comment by jmarmstrong1207** [comment]
> Looks like the author implented these changes in
> 
> [48b039b](https://github.com/crocodilestick/Calibre-Web-Automated/commit/48b039bb3e9de6d0ff77c4407b1854091e921f5e)
> 
> Thanks!

I can't see where he implemented the split feature. I'd keep your PR open

**Comment by jmarmstrong1207** [comment]
I just merged my PR providing instructions on how to create a development docker container as well! Check the readme, as it's just executing a bash script, then doing `docker compose` on the dev docker compose file in build/

**Comment by MrLemur** [comment]
> > @tucker87 Has this actually worked for you? The changes still cause the book to be added to the wrong folder, plus the book ingest function is broken now due to a misspelled variable name.
> 
> Which variable and error are you referencing?

The var name here is wrong: https://github.com/crocodilestick/Calibre-Web-Automated/blob/main/scripts/ingest-processor.py#L182

**Comment by jmarmstrong1207** [comment]
> > > @tucker87 Has this actually worked for you? The changes still cause the book to be added to the wrong folder, plus the book ingest function is broken now due to a misspelled variable name.
> > 
> > 
> > Which variable and error are you referencing?
> 
> The var name here is wrong: https://github.com/crocodilestick/Calibre-Web-Automated/blob/main/scripts/ingest-processor.py#L182

Just fixed it now. Should be pushed to the dev image soon

**Comment by jmarmstrong1207** [comment]
@MrLemur dev image has been pushed. Use my dev image: `jmarmstrong1207/calibre-web-automated:dev`

**Comment by MrLemur** [comment]
> @MrLemur dev image has been pushed. Use my dev image: `jmarmstrong1207/calibre-web-automated:dev`

I can confirm that now fixes any import issues.

**Pull request closed without merging**
