### PR TITLE
Port Generic Oauth Support

### LINKED ISSUE #90: [Feature Request] Generic OIDC/OAuth2 support
**Is your feature request related to a problem? Please describe.**
Calibre-web only supports SSO OAuth with external providers Google and Github.

**Describe the solution you'd like**
Adding a generic implementation would allow for authentication with any provider, most importantly allowing self-hosted solutions like [Authentik](https://github.com/goauthentik/authentik), [Authelia](https://github.com/authelia/authelia) and [Keycloak](https://github.com/keycloak/keycloak).

**Additional context**
This has been a topic of discussion for many years on Calibre-web, but the maintainer has said quite definitively that ["We will not extend Calibre-Web with any more login abilities"](https://github.com/janeczku/calibre-web/issues/2965#issuecomment-1875551176).

A [Pull Request](https://github.com/janeczku/calibre-web/pull/2211) was even made with this functionality, but sadly was never merged.

### PR DESCRIPTION
**Pull request by MattyIceee**
Fixes #90
I just brought over the pr [2211](https://github.com/janeczku/calibre-web/pull/2211) from the parent project to add generic oauth implementation. I am having trouble testing this as there seems to be an issue with the build.sh. Some help validating would be appreciated.

### CODE REVIEW

**Comment by crocodilestick** [comment]
Hey @MattyIceee, thanks for this! I've read about this whole debacle before on the CW GitHub. Could you please do your best to summarise the situation for me? As far as I can tell the original PR for this was very popular with users and the current head maintainer of CW refused to merge it based on personal biases (or did he have a point in the end?)

My questions would be:

- Has this still not been implemented into CW, and if so, do you know why?
- Upon adding this, what changes would be apparent to the average user? Is it something that is off by default or would it change the login in procedure for all users? 
- If added, would the changes be compatible with everyone's existing configuration files, or would it alter then that would then render them incompatible with stock CW?

Additionally regarding `build.sh`, did you edit the script with your own variables as instructed in the comments before running it?

**Comment by MattyIceee** [comment]
I got the image up and building but I'm bumping into an unrelated error (as in it happens even when I back out my changes).
After signing in with the default admin creds it looks like there's an issue with get_cwa_settings saying the list is empty and blowing up. Gonna try to build my changes off 2.1.2 as I'm not sure if the changes on the head are still being worked on.

**Comment by crocodilestick** [comment]
Build an image not with the current repo files as those are very much in active development for the next version, but using the files from the latest release (you can download an archive of them from the repo's Releases page)

**Comment by halkeye** [comment]
Is there a reason this was half merged? I can see some of the config in place, even an import in place, but random other stuff isn't here.

**Comment by halkeye** [comment]
oh, i think i understand whats going on.
This project takes upstream, and keeps files it wants to patch, its more of a wrapper than a fork.
I'm not sure how to contribute it in any sane way

**Pull request closed without merging**
