### PR TITLE
Update calibre-web release

### PR DESCRIPTION
**Pull request by kalpik**
This fixes metadata search issue

### CODE REVIEW

**Comment by crocodilestick** [comment]
It is unfortunatly no where near that easy to update the CW base-version 😅 However I have made the neccesary changes to main and they are currently being tested for bugs/stability in the dev channel prior to the next release

**Comment by kalpik** [comment]
Thanks! Just so you know, I am using a version with this change, and it at least fixes the metadata problem. I will wait for your "properly" fixed version, but in the meantime, at least I have metadata search working :P

**Comment by crocodilestick** [comment]
Good to know! I personally can't wait either! 😅 just a couple new features to finish up in the dev build and we should be good for a big release in the next couple weeks

**Comment by GinSoakedBoy** [comment]
Any updates on when the fix for this will be released?

@kalpik what did you change to get the 'fixed' version?

**Comment by kalpik** [comment]
> Any updates on when the fix for this will be released?
> 
> @kalpik what did you change to get the 'fixed' version?

You can use the :dev tag for the container to get a working version.

**Comment by GinSoakedBoy** [comment]
> > Any updates on when the fix for this will be released?
> > @kalpik what did you change to get the 'fixed' version?
> 
> You can use the :dev tag for the container to get a working version.

To be clear, you mean change image: crocodilestick/calibre-web-automated:latest to image: crocodilestick/calibre-web-automated:dev ?

**Comment by kalpik** [comment]
> > > Any updates on when the fix for this will be released?
> > > @kalpik what did you change to get the 'fixed' version?
> > 
> > 
> > You can use the :dev tag for the container to get a working version.
> 
> To be clear, you mean change image: crocodilestick/calibre-web-automated:latest to image: crocodilestick/calibre-web-automated:dev in the docker compose file?

That's correct. Keep in mind, that will switch you to the development version, which might have bugs and might break. You can switch back to the latest tag once the new version is released.

**Comment by GinSoakedBoy** [comment]
Ok, thanks. For some reason I'm still not getting any metadata results from Amazon.

**Pull request closed without merging**
